apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 8080
    targetPort: 8080
  selector:
    app: result
